In [1]:
# !pip install flask pandas python-dotenv openpyxl supabase
# !pip install supabase
# !pip install chardet

In [2]:
# pip show supabase

In [3]:
import pandas as pd
import glob
import os
import io

In [7]:
#main file ko ActivationDetailReport variable bna dia:
ActivationDetailReport = pd.read_csv(r"D:\i\uploads\raw\ActivationDetailReport_7GF0SCN8M.csv", encoding='latin1')

In [8]:
ActivationDetailReport

,marketid,storeid,company,custid,invno,serial,item,mobile,actdate,account,...,term,prodline,itmdesc,username,acttype,plancode,plantype1,grouptype,plandesc,mrc
0,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,86027,166750,'356795671974397,',3474479003,04-02-2026 15.48,515109926,...,NaN,NaN,NaN,BWH13560,Upgrade,35GBNP,Voice,Individual,$30 5GB AUTOPAY-$35 1ST MONTH,35
1,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,86027,166750,'356795671974397,',3474479003,04-02-2026 15.48,515109926,...,NaN,NaN,NaN,BWH13560,Upgrade,SCURE5S,Feature,Individual,NW SECURITY BUNDLE,5
2,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,86037,166761,'016759005739068,'610214687418,3474903183,04-02-2026 19.03,494167125,...,1 Year,METROPCS,TMO REVVL TAB 2 5G 64G BLK KIT,UBC25694,New Activation,TAB20SD,Voice,Individual,TABLET UNL SD VIDEO W/2GB HS,20
3,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,86056,166781,'016759005737708,'610214687418,6469945537,04-03-2026 12.35,333445370,...,1 Year,METROPCS,TMO REVVL TAB 2 5G 64G BLK KIT,UBC25694,New Activation,TAB20SD,Voice,Individual,TABLET UNL SD VIDEO W/2GB HS,20
4,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,86058,166784,'864644063338388,'610214714244,6465947190,04-03-2026 12.44,555403019,...,1 Year,METROPCS,ARC KVD21 GATEWAY BLK TMUS CPO,CGN92584,New Activation,HINTFOR,Voice,Individual,HOME INTERNET UNLTD PROMO PLAN,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,87080,167874,'358926211250554,',3477804852,04/30/2026 18:45:00,327118214,...,NaN,NaN,NaN,UBC25694,Reactivation,L344F100,Voice,Individual,PROMO 4 FOR 100 L4,10
334,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,87085,167879,'350321564356703,'887276865126,3476388822,04/30/2026 19:01:00,203772827,...,1 Year,METROPCS,SAM L305U GW7 40MM CRM KIT,BWH13560,New Activation,WATCHPR,Voice,Individual,SAMSUNG WATCH PAIRED,10
335,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,87085,167879,'861035062868892,'610214714244,3477344962,04/30/2026 19:01:00,203772827,...,1 Year,METROPCS,ARC KVD21 GATEWAY BLK TMUS CPO,BWH13560,New Activation,HINTFOR,Voice,Individual,HOME INTERNET UNLTD PROMO PLAN,45
336,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,87086,167881,'350321564356539,'887276865126,3478470525,04/30/2026 19:19:00,239612829,...,1 Year,METROPCS,SAM L305U GW7 40MM CRM KIT,BWH13560,New Activation,WATCHPR,Voice,Individual,SAMSUNG WATCH PAIRED,10
337,METRO-NY,C-70812973,DKS WIRELESS 2128007-DCWP,87086,167881,'864644062918719,'610214714244,3477342776,04/30/2026 19:19:00,239612829,...,1 Year,METROPCS,ARC KVD21 GATEWAY BLK TMUS CPO,BWH13560,New Activation,HINTFOR,Voice,Individual,HOME INTERNET UNLTD PROMO PLAN,45

In [9]:
#useful column ko alag variable me store kr dia:

useful_cols_ActivationDetailReport = ActivationDetailReport[['storeid','company','serial','acttype','plancode','plantype1',]]

In [10]:
useful_cols_ActivationDetailReport

,storeid,company,serial,acttype,plancode,plantype1
0,C-70812973,DKS WIRELESS 2128007-DCWP,'356795671974397,Upgrade,35GBNP,Voice
1,C-70812973,DKS WIRELESS 2128007-DCWP,'356795671974397,Upgrade,SCURE5S,Feature
2,C-70812973,DKS WIRELESS 2128007-DCWP,'016759005739068,New Activation,TAB20SD,Voice
3,C-70812973,DKS WIRELESS 2128007-DCWP,'016759005737708,New Activation,TAB20SD,Voice
4,C-70812973,DKS WIRELESS 2128007-DCWP,'864644063338388,New Activation,HINTFOR,Voice
...,...,...,...,...,...,...
333,C-70812973,DKS WIRELESS 2128007-DCWP,'358926211250554,Reactivation,L344F100,Voice
334,C-70812973,DKS WIRELESS 2128007-DCWP,'350321564356703,New Activation,WATCHPR,Voice
335,C-70812973,DKS WIRELESS 2128007-DCWP,'861035062868892,New Activation,HINTFOR,Voice
336,C-70812973,DKS WIRELESS 2128007-DCWP,'350321564356539,New Activation,WATCHPR,Voice
337,C-70812973,DKS WIRELESS 2128007-DCWP,'864644062918719,New Activation,HINTFOR,Voice

In [11]:
# sirf voice wale rows ko rakh lia baki ko hata dia:
useful_cols_ActivationDetailReport = useful_cols_ActivationDetailReport[useful_cols_ActivationDetailReport["plantype1"] == "Voice"]

In [13]:
# serial number me se non digit character ko hata dia:
useful_cols_ActivationDetailReport['serial'] = (useful_cols_ActivationDetailReport['serial'].astype(str).str.replace(r'\D', '', regex=True))

C:\Users\ithap\AppData\Local\Temp\ipykernel_160732\2714955539.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_cols_ActivationDetailReport['serial'] = (useful_cols_ActivationDetailReport['serial'].astype(str).str.replace(r'\D', '', regex=True))

In [14]:
# serial number ko dtype=int me convert kr dia:
useful_cols_ActivationDetailReport['serial'] = (
    useful_cols_ActivationDetailReport['serial']
    .astype(int)
)

C:\Users\ithap\AppData\Local\Temp\ipykernel_160732\3609367489.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_cols_ActivationDetailReport['serial'] = (

In [15]:
useful_cols_ActivationDetailReport.info()

<class 'pandas.core.frame.DataFrame'>
Index: 220 entries, 0 to 337
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   storeid    220 non-null    object
 1   company    220 non-null    object
 2   serial     220 non-null    int64
 3   acttype    220 non-null    object
 4   plancode   220 non-null    object
 5   plantype1  220 non-null    object
dtypes: int64(1), object(5)
memory usage: 12.0+ KB

In [16]:
# serial number ke count ko nikal lia:
serial_counts = useful_cols_ActivationDetailReport['serial'].value_counts().reset_index()

serial_counts.columns = ['serial', 'count']

print(serial_counts)

              serial  count
0    356795671974397      1
1     16759005739068      1
2     16759005737708      1
3    864644063338388      1
4    350153153301919      1
..               ...    ...
215  358926211250554      1
216  350321564356703      1
217  861035062868892      1
218  350321564356539      1
219  864644062918719      1

[220 rows x 2 columns]

In [18]:
# serial number ke count me se 1 se zyada wale ko nikal lia jisse pta chale kitne duplicate serial number hai:
duplicates = serial_counts[serial_counts['count'] > 1]

print(duplicates)

Empty DataFrame
Columns: [serial, count]
Index: []

this shows that there is no duplicate serial number present in ActivationDetailReport
And Bhavna said thet it will not have any.

Now moving towards curCallidus report we need esn=serial for maping

In [20]:
# CurCallidusReport file ko CurCallidusReport variable me import kia:
CurCallidusReport = pd.read_csv(r"D:\i\uploads\raw\curCallidus_7GF0SU2WW.csv", encoding='latin1')

In [21]:
# ye chargeback ke liye transaction_type_desc me se charge word ko search kr ke ek dictionary bna rha hai jisme esn ko key aur transaction_type_desc ko value rakh rha hai:

chargeback_dict = (
    CurCallidusReport[
        CurCallidusReport['transaction_type_desc']
        .str.contains('charge', case=False, na=False)
    ]
    .set_index('esn')['transaction_type_desc']
    .to_dict()
)

In [22]:
chargeback_dict

{}

In [23]:
CurCallidusReport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 54 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0.1             517 non-null    int64
 1   Unnamed: 0               517 non-null    int64
 2   marketid                 517 non-null    object
 3   custno                   517 non-null    object
 4   username                 451 non-null    object
 5   name                     451 non-null    object
 6   lastname                 451 non-null    object
 7   periodname               517 non-null    object
 8   dealerpositionname       517 non-null    object
 9   dealerfullname           517 non-null    object
 10  dealerregionname         0 non-null      float64
 11  dealeraddress            0 non-null      float64
 12  doorpositionname         517 non-null    int64
 13  doorfullname             517 non-null    object
 14  doorpayeeid              517 non-null    int64
 15  doorregionname           0 non-null      float64
 16  dooraddress              0 non-null      float64
 17  account_number           517 non-null    int64
 18  subscriber_id            517 non-null    int64
 19  mdn                      517 non-null    int64
 20  esn                      517 non-null    int64
 21  iccid                    517 non-null    object
 22  handset_model            502 non-null    object
 23  sku                      517 non-null    object
 24  transactiondate          517 non-null    object
 25  date_posted              439 non-null    object
 26  transaction_type         517 non-null    object
 27  sub_status               517 non-null    object
 28  ar_balance               517 non-null    float64
 29  esn_history              517 non-null    int64
 30  iccid_history            477 non-null    object
 31  transaction_type_desc    517 non-null    object
 32  rate_plan                0 non-null      float64
 33  bolt_on                  0 non-null      float64
 34  rate_plan_amount         0 non-null      float64
 35  bolt_on_amount           0 non-null      float64
 36  transaction_amount       517 non-null    float64
 37  status                   517 non-null    object
 38  businessrule             64 non-null     float64
 39  program_name             517 non-null    object
 40  tmonetwork_history_date  17 non-null     object
 41  carriername              9 non-null      object
 42  edge_login               0 non-null      float64
 43  qualificationday         471 non-null    float64
 44  rma                      0 non-null      float64
 45  originalsoc              517 non-null    object
 46  compsoc                  517 non-null    object
 47  compmrc                  471 non-null    float64
 48  custno1                  517 non-null    object
 49  fk_store                 517 non-null    int64
 50  tradeindeducted          0 non-null      float64
 51  periodnamedate           517 non-null    object
 52  callidusid               517 non-null    int64
 53  failedaudit              0 non-null      float64
dtypes: float64(17), int64(11), object(26)
memory usage: 218.2+ KB

In [24]:
#CurCallidusReport file me each unique esn ke hisab se transaction_amount ka sum nikal lia:
transaction_per_esn = CurCallidusReport.groupby('esn', as_index=False)['transaction_amount'].sum()

print(transaction_per_esn)
#jo esn=0 hai vo special revenue hai:

                 esn  transaction_amount
0                  0               275.0
1     15249003708225                25.0
2     16601007162552                25.0
3     16749000728125                21.4
4     16759005737708                11.0
..               ...                 ...
237  864644069560415                 0.0
238  866080076694137               137.5
239  866134075318238               300.0
240  867237078212321                20.0
241  999999999999999              -372.5

[242 rows x 2 columns]

In [25]:
# ab hum fin dkrege ki useful_cols_ActivationDetailReport['serial'] vs transaction_per_esn['esn'] me kitne common entries hai:

common_count = useful_cols_ActivationDetailReport['serial'].isin(
    transaction_per_esn['esn']
).sum()

print("Common entries:", common_count)

Common entries: 190

In [26]:
# Ab dekhege ki konse serial number jo useful_cols_ActivationDetailReport me hai vo transaction_per_esn me nahi hai:

unmatched = useful_cols_ActivationDetailReport[
    ~useful_cols_ActivationDetailReport['serial'].isin(transaction_per_esn['esn'])
]

print(unmatched[['serial']].head())

              serial
44   862503076150598
304  358433831467064
306  351458442795261
308  861857064088231
309  352380202474359

In [ ]:
#ab hum matching serial number ke hisab se transaction_amount ko useful_cols_ActivationDetailReport me naya column Rebate me le aate hai:
    
useful_cols_ActivationDetailReport['Rebate'] = (
    useful_cols_ActivationDetailReport['serial']
    .map(
        transaction_per_esn
        .set_index('esn')['transaction_amount']
    )
    .astype(float)
    .round(2)
)

C:\Users\ithap\AppData\Local\Temp\ipykernel_160732\1884502573.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_cols_ActivationDetailReport['Rebate'] = (

In [30]:
useful_cols_ActivationDetailReport['Rebate'] = (
    useful_cols_ActivationDetailReport['Rebate']
    .round(2)
)
print(useful_cols_ActivationDetailReport['Rebate'].dtype)

float64

C:\Users\ithap\AppData\Local\Temp\ipykernel_160732\1702325616.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_cols_ActivationDetailReport['Rebate'] = (

In [31]:
useful_cols_ActivationDetailReport.head()

,storeid,company,serial,acttype,plancode,plantype1,Rebate
0,C-70812973,DKS WIRELESS 2128007-DCWP,356795671974397,Upgrade,35GBNP,Voice,37.0
2,C-70812973,DKS WIRELESS 2128007-DCWP,16759005739068,New Activation,TAB20SD,Voice,11.0
3,C-70812973,DKS WIRELESS 2128007-DCWP,16759005737708,New Activation,TAB20SD,Voice,11.0
4,C-70812973,DKS WIRELESS 2128007-DCWP,864644063338388,New Activation,HINTFOR,Voice,41.0
5,C-70812973,DKS WIRELESS 2128007-DCWP,350153153301919,New Activation,4F100L1AP,Voice,21.0

In [ ]:
# check unique values in Rebate column
print(useful_cols_ActivationDetailReport['Rebate'].unique())

[37.   11.   41.   21.   29.   55.   25.   29.4  40.   27.4  36.25  9.
 19.   30.   15.   65.     nan 17.    0.   22.2  19.4  57.   45.   31.4
 31.   35.   27.5  50.   48.   27.   23.   23.4  26.2  21.4  33.4  29.8
  7.   42.5  41.67 20.  ]

In [35]:
#Now moving towards callidus report file 
CallidusReport = pd.read_csv(r"D:\i\uploads\raw\CallidusDetail_7GF0T17DL.csv",encoding="latin1")

In [36]:
CallidusReport.info()
# esn:int64             
# transaction_amount:float64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 45 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   marketid                 117 non-null    object
 1   custno                   117 non-null    object
 2   username                 117 non-null    object
 3   name                     117 non-null    object
 4   lastname                 117 non-null    object
 5   periodseq                0 non-null      float64
 6   periodname               117 non-null    object
 7   dealerpositionname       117 non-null    object
 8   dealerfullname           117 non-null    object
 9   dealerpayeeid            117 non-null    object
 10  dealerparticipantseq     0 non-null      float64
 11  dealerpositionseq        0 non-null      float64
 12  dealerregionname         0 non-null      float64
 13  dealeraddress            0 non-null      float64
 14  doorpositionname         117 non-null    int64
 15  doorfullname             117 non-null    object
 16  doorpayeeid              117 non-null    int64
 17  doorparticipantseq       0 non-null      float64
 18  doorpositionseq          0 non-null      float64
 19  doorregionname           0 non-null      float64
 20  dooraddress              0 non-null      float64
 21  account_number           117 non-null    int64
 22  subscriber_id            117 non-null    int64
 23  mdn                      117 non-null    int64
 24  esn                      117 non-null    int64
 25  iccid                    117 non-null    object
 26  handset_model            117 non-null    object
 27  sku                      117 non-null    object
 28  transactiondate          117 non-null    object
 29  program_name             117 non-null    object
 30  rebate_type              117 non-null    object
 31  qualification            117 non-null    object
 32  transaction_amount       117 non-null    float64
 33  date_posted              106 non-null    object
 34  rebate_transaction_type  117 non-null    object
 35  vendor_id                117 non-null    int64
 36  asap_login               117 non-null    int64
 37  custno1                  117 non-null    object
 38  fk_store                 117 non-null    int64
 39  qroffervalue             117 non-null    int64
 40  assurantassessedvalue    117 non-null    int64
 41  chargebackreason         0 non-null      float64
 42  rma                      0 non-null      float64
 43  periodnamedate           117 non-null    object
 44  callidusid               117 non-null    int64
dtypes: float64(12), int64(12), object(21)
memory usage: 41.3+ KB

In [38]:
# ab hum matching serial number ke hisab se transaction_amount ko useful_cols_ActivationDetailReport me naya column Compensation me le aate hai:

useful_cols_ActivationDetailReport['Compensation'] = (
    useful_cols_ActivationDetailReport['serial']
    .map(
        CallidusReport.set_index('esn')['transaction_amount']
    )
    .fillna(0.00)
    .astype(float)
    .round(2)
)

C:\Users\ithap\AppData\Local\Temp\ipykernel_160732\2259607981.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_cols_ActivationDetailReport['Compensation'] = (

In [39]:
useful_cols_ActivationDetailReport.head()

,storeid,company,serial,acttype,plancode,plantype1,Rebate,Compensation
0,C-70812973,DKS WIRELESS 2128007-DCWP,356795671974397,Upgrade,35GBNP,Voice,37.0,0.00
2,C-70812973,DKS WIRELESS 2128007-DCWP,16759005739068,New Activation,TAB20SD,Voice,11.0,118.20
3,C-70812973,DKS WIRELESS 2128007-DCWP,16759005737708,New Activation,TAB20SD,Voice,11.0,118.20
4,C-70812973,DKS WIRELESS 2128007-DCWP,864644063338388,New Activation,HINTFOR,Voice,41.0,49.01
5,C-70812973,DKS WIRELESS 2128007-DCWP,350153153301919,New Activation,4F100L1AP,Voice,21.0,0.00

In [40]:
# chargeback_dict se map karke pata chalega ki kaunse serial number chargeback hai:

useful_cols_ActivationDetailReport['Chargeback'] = (
    useful_cols_ActivationDetailReport['serial']
    .map(chargeback_dict)
)

C:\Users\ithap\AppData\Local\Temp\ipykernel_160732\4147988251.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  useful_cols_ActivationDetailReport['Chargeback'] = (

In [41]:
useful_cols_ActivationDetailReport.head()

,storeid,company,serial,acttype,plancode,plantype1,Rebate,Compensation,Chargeback
0,C-70812973,DKS WIRELESS 2128007-DCWP,356795671974397,Upgrade,35GBNP,Voice,37.0,0.00,NaN
2,C-70812973,DKS WIRELESS 2128007-DCWP,16759005739068,New Activation,TAB20SD,Voice,11.0,118.20,NaN
3,C-70812973,DKS WIRELESS 2128007-DCWP,16759005737708,New Activation,TAB20SD,Voice,11.0,118.20,NaN
4,C-70812973,DKS WIRELESS 2128007-DCWP,864644063338388,New Activation,HINTFOR,Voice,41.0,49.01,NaN
5,C-70812973,DKS WIRELESS 2128007-DCWP,350153153301919,New Activation,4F100L1AP,Voice,21.0,0.00,NaN

In [42]:
useful_cols_ActivationDetailReport.to_excel(
    "FinalizedReport.xlsx",
    index=False
)